ALTER TABLE users ADD COLUMN IF NOT EXISTS rts_rating INTEGER DEFAULT 1200;
ALTER TABLE users ADD COLUMN IF NOT EXISTS rts_games_played INTEGER DEFAULT 0;
ALTER TABLE users ADD COLUMN IF NOT EXISTS rts_games_won INTEGER DEFAULT 0;
